### ISSUE TITLE
Error in installation of vision

### ISSUE THREAD

**Issue by eralamdar** [stonne-simulator/stonne#14]
hello dear,
Is it possible to install STONNE on ubuntu18.04? which OS is recommended?
when I wanted to install vision this error was occured( i have attached it).
How I can solve this problem,please help

[](url
[error.docx](https://github.com/stonne-simulator/stonne/files/8099784/error.docx)
)

**Comment by Sairam954** [comment]
Hi,

I had a same issue, a simple workaround I used was to install vision using below command:
`pip install vision --no-deps`
This won't cause any problems to installed stonne torch
