### ISSUE TITLE
Steps to Install STONNE successfully

### ISSUE THREAD

**Issue by Sairam954** [stonne-simulator/stonne#19]
Hi all,

I have recently started using STONNE for my research. It is an awesome tool for modeling deep neural network accelerators. I am grateful to the authors for making it open-source. However, I ran into several issues while installing STONNE. I want to share the sequences of steps and commands that lead to a successful installation for me. The below steps have worked well for my lab mates too. 

Below are the steps:
1) Use VM or WSL with Ubunto 18.04
2) Install Anaconda
3) Setup a virtual environment using conda
`conda create --name stonne python=3.8 `
4) Activate stonne environment
`conda activate stonne `
5) Clone Stonne 
`git clone https://github.com/stonne-simulator/stonne.git`
6) Build  STONNE user interface
```
cd stonne
make all
```
The main issues with installation occur during the Pytorch-FrontEnd Installation of STONNE
7) Before beginning frontend installation, install numpy in the stonne env
`conda install -c anaconda numpy`
8) If you don't have CUDA access  e.g no graphic card, you need to export these environment variables before frontend installation
```
export MAX_JOBS=1
export NO_CUDA=YES
export NO_CUDA=1

```
9) Pytorch-frontend installation, it is important to set the CMAKE_PREFIX_PATH 
```
cd pytorch-frontend/
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install
```
10) You will encounter some module missing errors.  You can use conda to install modules one after the other module depending on the error or you install all of them at once using requirement.txt
The above step should build STONNE torch, the installation takes somewhere between 15-20mins depending on your machine.

11)  Once the installation is complete, then you need to connect the torch with stonne.
```
cd stonne_connection/
python setup.py install
```
12) You need torchvision for accessing various CNN models and datasets. The authors recommend building the vision from the source, but it throws several errors. The simple workaround that works without messing up the installed pytorch-stonne with below command:
`pip install torchvision --no-deps`
13) You can check the installation by running test-2.py in folder stonne-connection
 
Hope this helps in installing STONNE smoothly.

**Comment by Adrian-2105** [comment]
We updated the README with all the new steps you mentioned that were not previously included. We have also included some extra comments to make the installation easier. Finally, in case it might also be of interest, we have updated our Docker image to include the entire installed STONNE environment

Thanks a lot for your comments! :)

**Comment by ChaoGaoUCR** [comment]
Hi, I followed the guide in this repo,
However, I got stuck when I install the pytorch-frontend.
I keep getting errors like 
![image](https://github.com/stonne-simulator/stonne/assets/86901408/42bd4828-6983-4320-847f-79702ed34116)
Could you please help me take a look at this?
