### ISSUE TITLE
Cannot Run Benchmarks

### ISSUE THREAD

**Issue by ngiambla** [stonne-simulator/stonne#2]
I believe the scripts required to run the benchmarks were never committed.

**Comment by francisco-munoz** [comment]
Hi @ngiambla, you are right. This is a first version of the simulator. A further version with the benchmarks will be committed soon. We are waiting for the official publication to be accepted. In the mean time, if you wish, you can create your own benchmarks utilizing the explanation on the description.

Stay tuned!
Francisco

**Comment by jaylenwang7** [comment]
Hi, just wanted to follow up on this. What does the timeline look like in terms of releasing further version of the simulator?

**Comment by francisco-munoz** [comment]
hi @jaylenwang7,

Fortunately, stonne paper was published in IISWC'21 so we plan to push a further update before the conference. This means it will be by the end of October at most. Likely it will be earlier.

**Comment by ashsw** [comment]
Hi, sorry to bother you, but I cannot find the 4 DNN benchmarks in the benchmark files. Could you please tell me whether I'm looking in the wrong place or they haven't been uploaded yet?

**Comment by francisco-munoz** [comment]
Hi @ashsw @jaylenwang7 I added a few more benchmarks to the public repository. Probably you will have to edit your paths and download the weights (or train them). Please let me know if you have questions to set it up.

**Comment by ashsw** [comment]
Hi @francisco-munoz thank you very much for your reply and the update!

**Comment by ashsw** [comment]
Thank you very much for your kindness! There is one question: is there should be any file named cv2? Because there is one program statement "import cv2" both in the 'run_ssd_mobilenets.py'  and 'run_ssd_resnets.py'. But it seems cannot find in the file

**Comment by francisco-munoz** [comment]
I am happy to help @ashsw . I still want to further update the repository with new features. But I am involved in a few more projects and haven't had the time yet. I will try to update it by the christmas break. 

Regarding your question: cv2 is the opencv package used in python for computer vision. You should install it to run those benchmarks as they require some preprocessing with cv2.

**Comment by ashsw** [comment]
Thank you so much for your patient reply. I'm really sorry for bothering you before. I sincerely hope that your future research can have the expected results and make a major breakthrough!!

**Comment by francisco-munoz** [comment]
I am happy to help. It is not a bother at all. Thank you so much! Please do not hesitate to contact me if you have further questions.
