### ISSUE TITLE
Python-frontend installation errors

### ISSUE THREAD

**Issue by ChaoGaoUCR** [stonne-simulator/stonne#22]
Hi, Thanks for this great work,
I encountered the errors when I tried to build pytorch-frontend.
![image](https://github.com/stonne-simulator/stonne/assets/86901408/13f907cc-71e6-4804-b7ce-ccc4b547b333)
I knew there must be some path error I made,
But I can't find out. Could you please help me resolve this?

**Comment by Adrian-2105** [comment]
Hi! Yes, sure

Please, provide me more information so I can try to help you with this:

- When is that error prompting? During installation, when you try to `import torch_stonne`, ...?
- Did you use Anaconda for installation? Did you follow all commands listed on the README.md for installing the pytorch-frontend?
- Which OS are you using?
- Which Python version are you using?
- It would be great also if you can copy the commands you used for the installation, so I can also check them

**Comment by ChaoGaoUCR** [comment]
Sorry, It is my problem,
I found that my stonne_connection build is overwritten by some other package, when I rebuild, it is fixed.
But When I run AlexNet.py, I hit another mistake, could you please help me take a look at this?
<img width="900" alt="Screenshot 2023-05-10 at 10 16 01 PM" src="https://github.com/stonne-simulator/stonne/assets/86901408/271d4cf7-402e-41a4-b8bd-32e4fe9c2182">

**Comment by ChaoGaoUCR** [comment]
Sorry, My mistake,
I forgot to build the stonne_connection.
It got over-write when I pip install opencv2.
Thank you so much for your patience!
