### ISSUE TITLE
Pytorch Frontend Install Error

### ISSUE THREAD

**Issue by js4ngu** [stonne-simulator/stonne#26]
Hello.
I'm Jongsang Yoo , who is studying HW accelerator.
First of all, thank you for providing a good program as an open source. I think it will be very helpful for studying.

There is a problem with the PyTorch Frontend installation.
I have excutered all the commands in the readme file you provided. [ReadMe](https://github.com/stonne-simulator/stonne#installation-1)

![image](https://github.com/stonne-simulator/stonne/assets/30527114/ab93b218-2340-48ed-965b-61f9ef6a8878)
```bash
(stonne) jognsang@DESKTOP-TV817D3:~/lab/STONNE/stonne/pytorch-frontend$ python setup.py install
Building wheel torch-1.7.0a0+633fa53
-- Building version 1.7.0a0+633fa53
cmake -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/jognsang/lab/STONNE/stonne/pytorch-frontend/torch -DCMAKE_PREFIX_PATH=/home/jognsang/anaconda3/envs/stonne -DNUMPY_INCLUDE_DIR=/home/jognsang/anaconda3/envs/stonne/lib/python3.8/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/home/jognsang/anaconda3/envs/stonne/bin/python -DPYTHON_INCLUDE_DIR=/home/jognsang/anaconda3/envs/stonne/include/python3.8 -DPYTHON_LIBRARY=/home/jognsang/anaconda3/envs/stonne/lib/libpython3.8.so.1.0 -DTORCH_BUILD_VERSION=1.7.0a0+633fa53 -DUSE_NUMPY=True /home/jognsang/lab/STONNE/stonne/pytorch-frontend
Traceback (most recent call last):
  File "setup.py", line 748, in <module>
    build_deps()
  File "setup.py", line 327, in build_deps
    build_caffe2(version=version,
  File "/home/jognsang/lab/STONNE/stonne/pytorch-frontend/tools/build_pytorch_libs.py", line 54, in build_caffe2
    cmake.generate(version,
  File "/home/jognsang/lab/STONNE/stonne/pytorch-frontend/tools/setup_helpers/cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "/home/jognsang/lab/STONNE/stonne/pytorch-frontend/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/jognsang/anaconda3/envs/stonne/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/jognsang/anaconda3/envs/stonne/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/jognsang/anaconda3/envs/stonne/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/jognsang/anaconda3/envs/stonne/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'build'
```
However, the following error occurs.
How can I solve this problem?
Please give me some advice.

My environment is Window 10 + WSL 2 (Ubuntu 22.04).

ps. I confirmed that STONNE works with the STONNE User Interface.
![image](https://github.com/stonne-simulator/stonne/assets/30527114/17ac30bc-82cf-4421-ae9b-d40b1f21c3d1)

**Comment by js4ngu** [comment]
I deleted the file and tried it from the beginning, and it succeeded

**Comment by Adrian-2105** [comment]
Hi, I'm glad you were able to fix it. If you have any questions in the future, do not hesitate to ask again!

**Comment by js4ngu** [comment]
There is a problem with benchmark execution, so an error occurs in the process of deleting and reinstalling the repository.

The following error occurs. I solved it with "pip install torch" the other day.

However, this seemed to cause problems in the process of executing benchmark (torch.Cannot find simulated functions in nn)

Can you tell me how to solve it?
You have entered all commands in the readme in order. 

![image](https://github.com/stonne-simulator/stonne/assets/30527114/2eb186f4-b570-4b9c-84ed-13bacd5975e9)

(stonne) jognsang@DESKTOP-TV817D3:~/stonne/pytorch-frontend/stonne_connection$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils import cpp_extension
ModuleNotFoundError: No module named 'torch'

**Comment by Adrian-2105** [comment]
Hello again,

This happens because we use a specific PyTorch version, so if you install the most updated version of PyTorch through pip it won't work. You must install the version that is already included in the repository. In order to avoid version problems, we recommend to create an Anaconda environment and install PyTorch + STONNE connection inside it

Please, read carefully and follow the steps listed in the README about the Frontend installation. If the problem persists, then I can recommend you to work directly with the Docker image we created, which already have installed STONNE and its PyTorch extension: https://github.com/stonne-simulator/dockerfile

**Comment by js4ngu** [comment]
Thank you I i fixed with your solution :)
I always thanks to your kindly answer!
