### ISSUE TITLE
Question about the 'simulated_matmul()'

### ISSUE THREAD

**Issue by js4ngu** [stonne-simulator/stonne#27]
I have a question about the simulated_matmul() function.

The function seems to be porting the matmul() function to STONNE in pythorch.

Do torch.matmul() and torch_stonne.simulated_matmul() work exactly the same?

According to the notes, it should work the same way.

However, it does not seem to perform exactly the same motion in the following situations.
![image](https://github.com/stonne-simulator/stonne/assets/30527114/7814cc1b-e571-4c33-b28d-a56356e1b6e7)

```python
import torch
import torch_stonne

a = torch.tensor([[3],[0],[1],[2]])  # 1x4 matrix
b = torch.tensor([[0,2,2,3]])  # 4x2 matrix

r=torch_stonne.simulated_matmul("", a,  b, "../../simulation_files/maeri_128mses_128_bw.cfg", "test_tile.txt", 0)
print(r)
print(torch.matmul(a,b))
```

I want you to check it out

**Comment by js4ngu** [comment]
I did a little test.
There seems to be a problem when a Tensor composed of integers is input.

```python
import torch
import torch_stonne

print("TPU Test\n")
A = torch.randint(0, 10, (4, 1))
B = torch.randint(0, 10, (1, 4))
R = torch.matmul(A,B)

print("A :", A)
print("B :", B)
print("R : ")
print("PyTorch \n ",R)

print("STONNE\n")
r=torch_stonne.simulated_matmul("", A,  B, "../../simulation_files/maeri_128mses_128_bw.cfg", "test_tile.txt", 0)
print(r)
```

**Comment by Adrian-2105** [comment]
Hello,

Thanks for using STONNE. The purpose of the PyTorch Frontend is to be able to easily obtain the number of cycles required to compute each operation in the architecture. The number of cycles won't vary despite whether the result is correct or not. For that reason, the PyTorch Frontend actually only takes the main parameters from the tensors (dimensions, mainly) and uses them to initialize a random matrix and compute the operation using it. Thus, with the current implementation, it won't provide the correct output tensor for that operation. We are sorry about the inconvenience.

Hope this comment can help you.

**Comment by js4ngu** [comment]
So, is it impossible to compute an integer from STONNE?

**Comment by js4ngu** [comment]
If possible later, please.

I know this question is rude.
Do you happen to know a simulator that can also simulate the function of NPU (With cycle level simulate)?

**Comment by stonne-simulator** [comment]
Hello,

I am not aware of any other simulator. You could use the workaround of transforming the tensor from integer to float and process it on the simulator. Then you can convert again from float to integer. The simulation cycles will be the same as the size of the tensors will be identical. Does it make sense?

**Comment by js4ngu** [comment]
Thank you!
