### ISSUE TITLE
Error when trying to integrate the MADDPG with Stonne

### ISSUE THREAD

**Issue by kailashg26** [stonne-simulator/stonne#4]
Hello,
I'm trying to execute the MADDPG rl algorithm with stonne. But, I receive the following error. It says the tile cannot be parsed. But, MADDPG uses MLP neural network with nn.linear and I just did nn.SimulatedLinear.So, can you let me know where the problem might be?
python main.py simple_spread simple_spread --n_episodes 60000 --discrete_action
Episodes 1-2 of 60000
Traceback (most recent call last):
  File "main.py", line 251, in <module>
    run(config)
  File "main.py", line 125, in run
    torch_agent_actions, step_1_cnt, step_2_cnt = maddpg.step(torch_obs, step_1_cnt, step_2_cnt, explore=True)
  File "/home/kailash/Desktop/maddpg-pytorch-copy/algorithms/maddpg.py", line 92, in step
    action, counter_list = a.step(obs, counter_list, explore=explore)
  File "/home/kailash/Desktop/maddpg-pytorch-copy/utils/agents.py", line 75, in step
    action = self.policy(obs)
  File "/home/kailash/anaconda3/envs/maddpg-pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kailash/Desktop/maddpg-pytorch-copy/utils/networks.py", line 47, in forward
    h1 = self.nonlin(self.fc1(self.in_fn(X)))
  File "/home/kailash/anaconda3/envs/maddpg-pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kailash/anaconda3/envs/maddpg-pytorch/lib/python3.6/site-packages/torch/nn/modules/simulatedLinear.py", line 76, in forward
    output =  torch_stonne.simulated_linear_forward(self.__class__.__name__, input, self.weight, self.path_to_arch_file, self.path_to_tile, self.sparsity_ratio, True) # The last true is to transpose the matrices 
RuntimeError: dogsandcats_tile_fc.txt could not be opened for parsing

**Comment by kailashg26** [comment]
Hello, I'm using it for maddpg -pytorch version
Here by, I attach th MLP model (IN place of Linear, I just did nn.SimulatedLinear and ran the algorithm. But I got the above error (I input the dogsandcats_tile_fc.txt). I'm using this hardware file (maeri_128mses_64_bw.cfg)
maddpg pytorch source code: https://github.com/shariqiqbal2810/maddpg-pytorch 
class MLPNetwork(nn.Module):
    """
    MLP network (can be used as value or policy)
    """
    def __init__(self, input_dim, out_dim, hidden_dim=64, nonlin=F.relu,
                 constrain_out=False, norm_in=True, discrete_action=True):
        """
        Inputs:
            input_dim (int): Number of dimensions in input
            out_dim (int): Number of dimensions in output
            hidden_dim (int): Number of hidden dimensions
            nonlin (PyTorch function): Nonlinearity to apply to hidden layers
        """
        super(MLPNetwork, self).__init__()

        if norm_in:  # normalize inputs
            self.in_fn = nn.BatchNorm1d(input_dim)
            self.in_fn.weight.data.fill_(1)
            self.in_fn.bias.data.fill_(0)
        else:
            self.in_fn = lambda x: x
        self.fc1 = nn.Linear(input_dim, hidden_dim)#, '/home/kailash/Desktop/stonne/simulation_files/maeri_128mses_64_bw.cfg', 'dogsandcats_tile_fc.txt', sparsity_ratio=0.0)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)#, '/home/kailash/Desktop/stonne/simulation_files/maeri_128mses_64_bw.cfg', 'dogsandcats_tile_fc.txt', sparsity_ratio=0.0)
        self.fc3 = nn.Linear(hidden_dim, out_dim)#, '/home/kailash/Desktop/stonne/simulation_files/maeri_128mses_64_bw.cfg', 'dogsandcats_tile_fc.txt', sparsity_ratio=0.0)
        self.nonlin = nonlin
        if constrain_out and not discrete_action:
            # initialize small to prevent saturation
            self.fc3.weight.data.uniform_(-3e-3, 3e-3)
            self.out_fn = F.tanh
        else:  # logits for discrete action (will softmax later)
            self.out_fn = lambda x: x

    def forward(self, X):
        """
        Inputs:
            X (PyTorch Matrix): Batch of observations
        Outputs:
            out (PyTorch Matrix): Output of network (actions, values, etc)
        """
        h1 = self.nonlin(self.fc1(self.in_fn(X)))
        h2 = self.nonlin(self.fc2(h1))
        out = self.out_fn(self.fc3(h2))
        return out

**Comment by francisco-munoz** [comment]
Given the above error, I just note that it seems the interface cannot read the tile file (i.e., dogsandcat_tile_fc.txt). Are you sure you are including the file? You are not specifying any path to the file. Is it in your working directory? Remember you can find the file in minibenchmarks folder. Let me know if It works when indicating the whole path to the file.
