### ISSUE TITLE
Can we implement training on STONNE?

### ISSUE THREAD

**Issue by kailashg26** [stonne-simulator/stonne#5]
Hi Francisco Muñoz-Martínez,
Can we train an algorithm on STONNE? If not, can you guide me through the ways on (any documentation) to change the simulator to accelerate training?

**Comment by francisco-munoz** [comment]
Hi @kailashg26 ,

Currently the simulator only supports nn.Conv, nn.Linear, nn.matmul and nn.sparsematmul. However, in essence, the simulator is a framework able to run the kernels GEMM, SpGEMM and CONV (among some others). You can use those kernels in your specific operation. What do you want to do exactly? Please, if you want me to further help you out email me at francisco.munoz2@um.es

**Comment by kailashg26** [comment]
I just sent an email. I described my problem in the mail.
Thanks francisco, hope to receive your reply soon.
